# Generated by Django 5.1.4 on 2024-12-15 16:31

import users.usermanager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_users_managers_users_date_joined_users_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[
                ("objects", users.usermanager.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="users",
            name="phone_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
