# Generated by Django 5.1.4 on 2025-01-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_users_address_users_date_of_birth_users_profile_pic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("AD", "Admin"), ("CU", "Customer")],
                default="CU",
                max_length=200,
            ),
        ),
    ]
