# Generated by Django 5.1.4 on 2025-01-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_users_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
