# Generated by Django 5.1.4 on 2025-01-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_item_total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
