# Generated by Django 5.1.4 on 2025-01-01 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="reviews.rating"
            ),
        ),
    ]
