# Generated by Django 5.1.4 on 2024-12-30 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="total_price",
            new_name="item_total_price",
        ),
    ]
